export const hotels = [
  {
    hotel_id: 1,
    name: "Grand Plaza Hotel",
    location: {
      address: "123 Main St, Cityville",
      city: "Cityville",
      state: "State",
      zip: "12345",
      country: "Country",
    },
    rating: 4.5,
    rooms_available: 10,
    price_per_night: 150.0,
    amenities: [
      "Free Wi-Fi",
      "Swimming Pool",
      "Fitness Center",
      "Restaurant",
      "Bar",
    ],
    image: "https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg",
  },
  {
    hotel_id: 2,
    name: "Cozy Cottage Inn",
    location: {
      address: "456 Lakeview Rd, Countryside",
      city: "Countryside",
      state: "State",
      zip: "67890",
      country: "Country",
    },
    rating: 4.0,
    rooms_available: 5,
    price_per_night: 120.0,
    amenities: ["Free Breakfast", "Pet Friendly", "Parking", "Free Wi-Fi"],
    image: "https://images.pexels.com/photos/4713251/pexels-photo-4713251.jpeg",
  },
  {
    hotel_id: 3,
    name: "Luxury Resort",
    location: {
      address: "789 Ocean Blvd, Beachside",
      city: "Beachside",
      state: "State",
      zip: "54321",
      country: "Country",
    },
    rating: 5.0,
    rooms_available: 20,
    price_per_night: 300.0,
    amenities: [
      "Spa",
      "Private Beach",
      "Infinity Pool",
      "24/7 Room Service",
      "Free Wi-Fi",
      "Fitness Center",
    ],
    image: "https://images.pexels.com/photos/4119831/pexels-photo-4119831.jpeg",
  },
  {
    hotel_id: 4,
    name: "Urban Stay Hotel",
    location: {
      address: "321 Downtown Ave, Metropolis",
      city: "Metropolis",
      state: "State",
      zip: "98765",
      country: "Country",
    },
    rating: 4.2,
    rooms_available: 15,
    price_per_night: 180.0,
    amenities: [
      "Free Wi-Fi",
      "Rooftop Bar",
      "Conference Rooms",
      "Gym",
      "Airport Shuttle",
    ],
    image: "https://images.pexels.com/photos/3144580/pexels-photo-3144580.jpeg",
  },
];
